analytics:
  google: UA-74878128-1
color:
  brandColors:
    - '#d8deea'
    - '#0c1124'
    - '#4f5f81'
    - '#9ea9bd'
    - '#283650'
  brandStrength: 0.5625
  lightness: 0.3125
  rhythmicContrast: 0.75
  saturation: 0.1875
cta: {}
layout_spectrum: 0.639639
name: Dark Heights
opengraph: {}
purpose: []
typography_spectrum: 1
