name: Dark Heights
favicon: null
layout_spectrum: 0.82587
typography_spectrum: 0.82829
title: Dark Heights
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74878128-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8deea'
    - '#0c1124'
    - '#4f5f81'
    - '#9ea9bd'
    - '#283650'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
